name: Call Reusable Workflow
on:
  push:
    branches:
      - main
      - master

jobs:
  use-reusable:
    uses: Koshkorovsky/2402-first-repo/.github/workflows/reusable-test.yaml@master
    with:
      cool_var: "amazing"
